name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - '1.13'
          - '1.18'
          - '1.19'
          - '1.20'
          - '1.21'
          - '1.22'
    steps:
    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v4
    - name: Get dependencies
      run: go get -v -t -d ./...
    - name: Build
      run: go build -v .
    - name: Build Example
      run: |
        cd example
        go build -v .
